---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezdataviz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ezdataviz-pod

  template:
    metadata:
      labels:
        app: ezdataviz-pod
    spec:
      containers:
        - name: ezdataviz-pod
          image: rahools/ez-data-viz # to fill
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ezdataviz-service
spec:
  selector:
    app: ezdataviz-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 80
  type: LoadBalancer